# Generated by Django 5.2.3 on 2025-08-04 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaspberryPiEndpoint',
            fields=[
                ('pi_endpoint_id', models.CharField(help_text='ID duy nhất cho endpoint, ví dụ: send-data, reboot-cmd...', max_length=100, primary_key=True, serialize=False)),
                ('path', models.CharField(help_text='Path endpoint mà Raspi đang chạy, ví dụ: /api/send_data/', max_length=255)),
                ('description', models.CharField(blank=True, help_text='Mô tả chức năng endpoint nếu cần', max_length=255, null=True)),
                ('raspberry_pi', models.ForeignKey(help_text='Thiết bị Raspberry Pi tương ứng', on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='iot_app.raspberrypi')),
            ],
        ),
    ]
