# Generated by Django 5.2.3 on 2025-07-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='cpu_temperature_celsius',
            field=models.FloatField(default=0.0, help_text='Nhiệt độ CPU hiện tại (°C)'),
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='cpu_usage',
            field=models.FloatField(default=0.0, help_text='Mức sử dụng CPU hiện tại (%)'),
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='disk_space_gb',
            field=models.FloatField(default=0.0, help_text='Dung lượng ổ đĩa còn trống (GB)'),
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='ram_usage_gb',
            field=models.FloatField(default=0.0, help_text='Mức sử dụng RAM hiện tại (GB)'),
        ),
    ]
