# Generated by Django 5.2.3 on 2025-07-12 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0002_raspberrypi_cpu_temperature_celsius_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiMetricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('CPU', 'CPU Usage'), ('RAM', 'RAM Usage (GB)'), ('DISK', 'Disk Space (GB)'), ('TEMP', 'CPU Temperature (C)')], help_text='Loại metric (CPU, RAM, TEMP, DISK)', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Thời gian ghi nhận metric')),
                ('value', models.FloatField(help_text='Giá trị của metric tại thời điểm này')),
                ('raspberry_pi', models.ForeignKey(help_text='Raspberry Pi mà bản ghi metric này thuộc về', on_delete=django.db.models.deletion.CASCADE, related_name='metric_history', to='iot_app.raspberrypi')),
            ],
            options={
                'verbose_name_plural': 'Pi Metric Histories',
                'ordering': ['timestamp'],
                'unique_together': {('raspberry_pi', 'metric_type', 'timestamp')},
            },
        ),
    ]
