# Generated by Django 5.2.3 on 2025-08-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0002_raspberrypiendpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServiceConfig',
            fields=[
                ('server_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('service_type', models.CharField(choices=[('MQTT', 'MQTT Broker'), ('SQL', 'SQL Server'), ('HTTP_API', 'HTTP API')], max_length=20)),
                ('host', models.CharField(max_length=200)),
                ('port', models.PositiveIntegerField(default=1883)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='RaspberryPiEndpoint',
        ),
    ]
