# Generated by Django 5.2.3 on 2025-08-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0003_externalserviceconfig_delete_raspberrypiendpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalserviceconfig',
            name='service_type',
            field=models.CharField(choices=[('MQTT', 'MQTT Broker'), ('SQL', 'SQL Server'), ('HTTP_API', 'HTTP API'), ('HTTP to MQTT Proxy Server', 'HTTP_MQTT_PROXY')], max_length=200),
        ),
    ]
