# Generated by Django 5.2.3 on 2025-07-25 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0004_raspberrypi_timezone_alter_sensor_sensor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorTemperatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_interval_seconds', models.PositiveIntegerField(default=300, help_text='Chu kỳ đọc dữ liệu (giây)')),
                ('threshold_high', models.FloatField(default=50.0, help_text='Ngưỡng cảnh báo cao (°C)')),
                ('threshold_low', models.FloatField(default=10.0, help_text='Ngưỡng cảnh báo thấp (°C)')),
                ('sensor', models.OneToOneField(help_text='Chỉ áp dụng cho cảm biến nhiệt độ', limit_choices_to={'sensor_type': 'temperature'}, on_delete=django.db.models.deletion.CASCADE, related_name='temperature_config', to='iot_app.sensor')),
            ],
        ),
    ]
