# Generated by Django 5.2.3 on 2025-07-28 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0005_sensortemperatureconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundSensorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gain_multiplier', models.IntegerField(choices=[(25, '25x Gain'), (60, '60x Gain'), (125, '125x Gain')], default=60, help_text='Hệ số khuếch đại tín hiệu âm thanh (ví dụ: 25, 60, 125).')),
                ('sampling_interval_ms', models.PositiveIntegerField(default=100, help_text='Thời gian lấy mẫu ADC của vi điều khiển (mili giây).')),
                ('sound_threshold_mv', models.FloatField(default=300.0, help_text='Ngưỡng điện áp analog (mV) từ cảm biến để phát hiện sự kiện âm thanh.')),
                ('hold_time_ms', models.PositiveIntegerField(default=500, help_text='Thời gian tối thiểu (ms) âm thanh phải vượt ngưỡng để kích hoạt sự kiện.')),
                ('read_interval_seconds', models.PositiveIntegerField(default=60, help_text='Chu kỳ gửi dữ liệu định kỳ về server (giây), bất kể có sự kiện.')),
                ('operating_mode', models.CharField(choices=[('CONTINUOUS', 'Liên tục (gửi định kỳ)'), ('EVENT_TRIGGERED', 'Kích hoạt sự kiện (chỉ gửi khi vượt ngưỡng)'), ('HYBRID', 'Kết hợp (định kỳ & sự kiện)')], default='CONTINUOUS', help_text='Chế độ hoạt động của cảm biến (liên tục, sự kiện, kết hợp).', max_length=20)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sound_config', to='iot_app.sensor')),
            ],
        ),
    ]
