# Generated by Django 5.2.3 on 2025-07-28 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0006_soundsensorconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundsensorconfig',
            name='sensor',
            field=models.OneToOneField(help_text='Chỉ áp dụng cho cảm biến âm thanh', limit_choices_to={'sensor_type': 'sound'}, on_delete=django.db.models.deletion.CASCADE, related_name='sound_config', to='iot_app.sensor'),
        ),
    ]
