# Generated by Django 5.2.3 on 2025-07-28 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0007_alter_soundsensorconfig_sensor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoundSensorConfig',
            new_name='SensorSoundConfig',
        ),
    ]
