# Generated by Django 5.2.3 on 2025-07-28 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0008_rename_soundsensorconfig_sensorsoundconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='protocol_with_esp',
            field=models.CharField(choices=[('I2C', 'I2C'), ('SPI', 'SPI'), ('ONEWIRE', 'OneWire'), ('ANALOG_PIN', 'Analog Pin'), ('DIGITAL_PIN', 'Digital Pin'), ('UART', 'UART')], default='ANALOG_PIN', help_text='Giao thức ESP32 sử dụng để đọc cảm biến này', max_length=20),
        ),
        migrations.CreateModel(
            name='SensorVibrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibration_threshold_mv', models.FloatField(default=500.0, help_text='Ngưỡng phát hiện rung động. Nếu là analog, là giá trị ADC. Nếu là digital, là ngưỡng logic.')),
                ('debounce_time_ms', models.PositiveIntegerField(default=100, help_text='Thời gian tối thiểu (ms) giữa hai lần phát hiện rung động liên tiếp để tránh nhiễu.')),
                ('sampling_interval_ms', models.PositiveIntegerField(default=100, help_text='Thời gian lấy mẫu ADC của vi điều khiển (mili giây).')),
                ('operating_mode', models.CharField(choices=[('CONTINUOUS', 'Liên tục (gửi định kỳ cường độ)'), ('EVENT_TRIGGERED', 'Kích hoạt sự kiện (chỉ gửi khi vượt ngưỡng)'), ('HYBRID', 'Kết hợp (định kỳ & sự kiện)')], default='CONTINUOUS', help_text='Chế độ hoạt động của cảm biến rung.', max_length=20)),
                ('read_interval_seconds', models.PositiveIntegerField(default=60, help_text='Chu kỳ gửi dữ liệu định kỳ về server (giây), áp dụng ở chế độ liên tục/kết hợp.')),
                ('sensor', models.OneToOneField(help_text='Chỉ áp dụng cho cảm biến rung động', limit_choices_to={'sensor_type': 'vibration'}, on_delete=django.db.models.deletion.CASCADE, related_name='vibration_config', to='iot_app.sensor')),
            ],
        ),
    ]
