# Generated by Django 5.2.3 on 2025-07-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0009_sensor_protocol_with_esp_sensorvibrationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='espdevice',
            name='esp_firmware',
            field=models.CharField(blank=True, help_text='Phiên bản firmware', max_length=200, null=True),
        ),
    ]
