# Generated by Django 5.2.3 on 2025-07-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0010_espdevice_esp_firmware'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.CharField(choices=[('°C', 'Độ C'), ('°F', 'Độ F'), ('%', '% Độ ẩm'), ('mV', 'mV'), ('', 'Không rõ')], default='', help_text='Đơn vị đo của cảm biến (người dùng có thể chọn)', max_length=10),
        ),
    ]
