# Generated by Django 5.2.3 on 2025-07-07 04:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('guidance', models.TextField(max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image_Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tên hoặc mô tả ngắn gọn về hình ảnh.', max_length=255)),
                ('image', models.ImageField(upload_to='tutor_app')),
                ('description', models.TextField(help_text='Mô tả hình cho AI hiểu', max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('exercise', models.ForeignKey(help_text='Bài tập mà hình ảnh này thuộc về.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tutor_app.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='LogFile_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_file', models.CharField(help_text='Khóa đối tượng (object key) của file log trao đổi với AI trên GCS.', max_length=255, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Account_Student',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_app.student')),
            ],
        ),
    ]
