# Generated by Django 5.2.3 on 2025-07-07 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0002_lession_exercise_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('system_rule', models.TextField(help_text='Quy tắc hệ thống hoặc hướng dẫn cho AI khi tương tác trong khóa học này.')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AddField(
            model_name='lession',
            name='course',
            field=models.ForeignKey(help_text='Buổi học mà bài tập này thuộc về.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessions', to='tutor_app.course'),
        ),
    ]
