# Generated by Django 5.2.3 on 2025-07-07 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0003_course_alter_exercise_description_lession_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='tutor_app.course'),
        ),
        migrations.CreateModel(
            name='ReultExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_process', 'Đang làm'), ('complete', 'Hoàn thành')], default='in_process', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Điểm không được nhỏ hơn 0.'), django.core.validators.MaxValueValidator(10, message='Điểm không được lớn hơn 10.')])),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_app.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_app.student')),
            ],
            options={
                'unique_together': {('student', 'exercise')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='exercises',
            field=models.ManyToManyField(related_name='students_done', through='tutor_app.ReultExercise', to='tutor_app.exercise'),
        ),
    ]
