# Generated by Django 5.2.3 on 2025-07-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0004_student_courses_reultexercise_student_exercises'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReultExercise',
            new_name='ResultExercise',
        ),
    ]
