# Generated by Django 5.2.3 on 2025-07-07 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0005_rename_reultexercise_resultexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_student',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='tutor_app.student'),
        ),
        migrations.AlterField(
            model_name='logfile_student',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='tutor_app.student'),
        ),
    ]
